project:
  type: website
  output-dir: docs
  resources:
    - CV.pdf

website:
  title: "Dr. Fabian R. Ketwaroo"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects
      - text: Presentations
        href: presentations
     
    

format:
  html:
    grid: 
      body-width: 3000px
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

