project:
  type: website
  resources:
    - CV.pdf

website:
  title: "Dr. Fabian R. Ketwaroo"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - CV.qmd
      - projects.qmd
      - talks.qmd
      

format:
  html:
    grid: 
      body-width: 3000px
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

