---
title: "A New Modeling Framework for Roost Count Data."
toc: false
---

Roost counts, where individuals of a species are counted whilst arriving or departing from their roost site, are an important monitoring tool for several species around the world. However, the raw count data are an underestimate of the size of the monitored population at any one time because of individuals temporarily not using the roost (temporary emigration, TE) and because the probability of detection of individuals, even when using the roost, is typically much lower than one (observation error). In this paper, we develop a novel modelling framework for estimating population size, from roost count data, while accounting for both TE and observation error. Our framework builds on the popular class of N-mixture models but extends them in a number of ways. Specifically, we introduce two model classes for TE, a parametric, which relies on temporal models, and a non-parametric, which relies on Dirichlet process mixture models. Both model classes give rise to interesting ecological interpretations of the TE pattern while being parsimonious in terms of the number of parameters required to model the pattern. When accounting for observation error, we use mixed-effects models and implement an efficient Bayesian variable selection algorithm for identifying important predictors for the probability of detection. We demonstrate our new modelling framework using an extensive simulation study, which highlights the importance of using mixed-effects models for the probability of detection and illustrates the performance of the model when estimating population size and underlying TE patterns. We also assess the ability of the corresponding variable selection algorithm to identify important predictors under different scenarios for observation error and its corresponding model. When fitted to two motivating data sets of parrots, our results provide new insights into how each species uses the roost throughout the year, on changes in population size between and within years, and on important predictors for observation error. 

SUBMITTED TO ANNALS OF APPLIED STATISTICS. In review.

Latest draft available [here](A-new-modelling-framework-for-roost-count-data.pdf)
